services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slotory-app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - media:/app/media
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - slotory-net

  mongo:
    image: mongo:7
    container_name: slotory-mongo
    restart: unless-stopped
    command: ['--storageEngine', 'wiredTiger']
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.runCommand({ ping: 1 }).ok']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - slotory-net

  nginx:
    image: nginx:alpine
    container_name: slotory-nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - certbot-web:/var/www/certbot:ro
      - certbot-certs:/etc/letsencrypt:ro
    depends_on:
      - app
    networks:
      - slotory-net

  certbot:
    image: certbot/certbot
    container_name: slotory-certbot
    volumes:
      - certbot-web:/var/www/certbot
      - certbot-certs:/etc/letsencrypt
    entrypoint: ['/bin/sh', '-c']
    command: ['trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done']
    networks:
      - slotory-net

volumes:
  mongo-data:
  media:
  certbot-web:
  certbot-certs:

networks:
  slotory-net:
    driver: bridge
