import nextPlugin from '@next/eslint-plugin-next'
import eslintConfigPrettier from 'eslint-config-prettier/flat'
import tseslint from 'typescript-eslint'

// `@next/eslint-plugin-next` ships ready-to-use flat-config objects:
// `recommended` and `core-web-vitals`. We spread them directly instead of
// going through `FlatCompat` (the legacy bridge triggers a circular-structure
// bug when ESLint validates the embedded `react` plugin reference).
const nextCoreWebVitals = /** @type {any} */ (nextPlugin).configs['core-web-vitals']

const eslintConfig = [
  // Next.js core-web-vitals rules (react, react-hooks, jsx-a11y, @next/next).
  nextCoreWebVitals,
  // TypeScript rules — parser + plugin, applies to .ts/.tsx only.
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: { jsx: true },
      },
    },
    rules: {
      '@typescript-eslint/ban-ts-comment': 'warn',
      '@typescript-eslint/no-empty-object-type': 'warn',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/consistent-type-imports': [
        'warn',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          vars: 'all',
          args: 'after-used',
          ignoreRestSiblings: false,
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^(_|ignore)',
        },
      ],
    },
  },
  {
    ignores: [
      '.next/',
      '.husky/',
      'build/',
      'dist/',
      'coverage/',
      'node_modules/',
      'playwright-report/',
      'test-results/',
      // Auto-generated by Payload — do not lint.
      'src/payload-types.ts',
      'src/payload-generated-schema.ts',
      'src/app/(payload)/**',
    ],
  },
  // Prettier must always be LAST so it disables conflicting stylistic rules.
  eslintConfigPrettier,
]

export default eslintConfig
