/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'user-notes': UserNote;
    'schedule-slots': ScheduleSlot;
    groups: Group;
    subscriptions: Subscription;
    'credit-transactions': CreditTransaction;
    documents: Document;
    payments: Payment;
    'sick-leaves': SickLeaf;
    'landing-blocks': LandingBlock;
    'landing-pages': LandingPage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'user-notes': UserNotesSelect<false> | UserNotesSelect<true>;
    'schedule-slots': ScheduleSlotsSelect<false> | ScheduleSlotsSelect<true>;
    groups: GroupsSelect<false> | GroupsSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    'credit-transactions': CreditTransactionsSelect<false> | CreditTransactionsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    'sick-leaves': SickLeavesSelect<false> | SickLeavesSelect<true>;
    'landing-blocks': LandingBlocksSelect<false> | LandingBlocksSelect<true>;
    'landing-pages': LandingPagesSelect<false> | LandingPagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Полное имя (генерируется автоматически из ФИО).
   */
  name?: string | null;
  /**
   * Фамилия
   */
  lastName?: string | null;
  /**
   * Имя
   */
  firstName?: string | null;
  /**
   * Отчество (необязательно)
   */
  middleName?: string | null;
  /**
   * Дата рождения
   */
  birthDate?: string | null;
  /**
   * Телефон родителя (обязательно для учащихся до 18 лет).
   */
  parentPhone?: string | null;
  role: 'user' | 'parent' | 'trainer' | 'admin';
  /**
   * Законный представитель ученика (роль «Родитель»).
   */
  parent?: (string | null) | User;
  avatar?: (string | null) | Media;
  /**
   * IANA timezone, e.g. Europe/Moscow
   */
  timezone?: string | null;
  /**
   * За сколько часов до тренировки присылать напоминание (0 — отключить).
   */
  reminderLeadHours?: number | null;
  /**
   * Arbitrary user preferences (UI state, notifications, …).
   */
  preferences?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  owner?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-notes".
 */
export interface UserNote {
  id: string;
  title: string;
  content?: string | null;
  owner: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-slots".
 */
export interface ScheduleSlot {
  id: string;
  /**
   * Дата и время начала тренировки.
   */
  startAt: string;
  durationMin: number;
  /**
   * Индивидуальная (один ученик) или групповая тренировка.
   */
  kind: 'individual' | 'group';
  /**
   * Заполняется только для индивидуальной тренировки.
   */
  student?: (string | null) | User;
  /**
   * Заполняется только для групповой тренировки.
   */
  group?: (string | null) | Group;
  status: 'planned' | 'done' | 'cancelled';
  /**
   * План тренировки или комментарии тренера.
   */
  notes?: string | null;
  /**
   * Повторять слот по расписанию.
   */
  isRecurring?: boolean | null;
  recurrence?: {
    frequency: 'daily' | 'weekly';
    /**
     * Каждую N-ю неделю/день (1..4).
     */
    interval: number;
    /**
     * Дни недели (0=Вс … 6=Сб). Только для еженедельного повторения.
     */
    weekdays?: number[] | null;
    /**
     * Дата окончания серии (необязательно, если задано количество).
     */
    until?: string | null;
    /**
     * Количество повторений (необязательно, если задана дата окончания).
     */
    count?: number | null;
    /**
     * IANA timezone, в которой задано время начала серии.
     */
    timezone: string;
  };
  isRecurringChild?: boolean | null;
  recurrenceParent?: (string | null) | ScheduleSlot;
  /**
   * Журнал посещаемости (управляется через UI, не через админку).
   */
  attendance?:
    | {
        student: string | User;
        present?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups".
 */
export interface Group {
  id: string;
  name: string;
  /**
   * Ученики, входящие в группу.
   */
  members?: (string | User)[] | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: string;
  student: string | User;
  kind: 'individual' | 'group';
  /**
   * Сколько занятий куплено.
   */
  totalCredits: number;
  /**
   * Осталось занятий (управляется системой).
   */
  remainingCredits: number;
  /**
   * Начало действия абонемента.
   */
  validFrom: string;
  /**
   * Окончание действия абонемента.
   */
  validUntil: string;
  status: 'active' | 'expired' | 'closed';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-transactions".
 */
export interface CreditTransaction {
  id: string;
  student: string | User;
  subscription: string | Subscription;
  /**
   * Слот, за который списано занятие (если применимо).
   */
  slot?: (string | null) | ScheduleSlot;
  /**
   * +N при покупке, −1 при списании.
   */
  delta: number;
  reason: 'purchase' | 'session' | 'refund' | 'adjustment';
  /**
   * Остаток на абонементе после операции.
   */
  balanceAfter?: number | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: string;
  /**
   * Ученик, к которому относится документ.
   */
  student: string | User;
  docType: 'medic' | 'contract' | 'other';
  title: string;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: string;
  student: string | User;
  /**
   * Связанный абонемент (необязательно).
   */
  subscription?: (string | null) | Subscription;
  /**
   * Сумма платежа.
   */
  amount: number;
  currency?: ('RUB' | 'USD' | 'EUR') | null;
  /**
   * Начало оплаченного периода.
   */
  periodFrom: string;
  /**
   * Конец оплаченного периода.
   */
  periodTo: string;
  method?: ('cash' | 'card' | 'transfer') | null;
  /**
   * Дата платежа.
   */
  paidAt: string;
  /**
   * Чек / квитанция (документ).
   */
  receipt?: (string | null) | Document;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sick-leaves".
 */
export interface SickLeaf {
  id: string;
  student: string | User;
  /**
   * Тренировка, по которой подан больничный.
   */
  slot: string | ScheduleSlot;
  /**
   * Описание болезни / причина.
   */
  reason: string;
  /**
   * Медицинская справка (необязательно).
   */
  document?: (string | null) | Document;
  status: 'pending' | 'approved' | 'rejected';
  reviewedAt?: string | null;
  /**
   * Комментарий тренера при рассмотрении.
   */
  reviewNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-blocks".
 */
export interface LandingBlock {
  id: string;
  /**
   * Internal label for this block (not shown on site).
   */
  title: string;
  blockType:
    | 'hero'
    | 'audience'
    | 'problems'
    | 'features'
    | 'gamification'
    | 'parentControl'
    | 'trainerDashboard'
    | 'aiAssistant'
    | 'extraFeatures'
    | 'howItWorks'
    | 'advantages'
    | 'testimonials'
    | 'pricing'
    | 'faq'
    | 'finalCta';
  heading?: string | null;
  subheading?: string | null;
  ctaText?: string | null;
  ctaTextSecondary?: string | null;
  /**
   * Background image for Hero (full viewport).
   */
  backgroundImage?: (string | null) | Media;
  items?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  cards?:
    | {
        icon?: string | null;
        title: string;
        subtitle?: string | null;
        items?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  steps?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  dashboardCards?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  testimonials?:
    | {
        text: string;
        rating?: number | null;
        id?: string | null;
      }[]
    | null;
  pricing?:
    | {
        name: string;
        price: string;
        features?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        popular?: boolean | null;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  advantages?:
    | {
        icon?: string | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages".
 */
export interface LandingPage {
  id: string;
  /**
   * Internal name for this page.
   */
  title: string;
  /**
   * Mark this page as active — it will be shown at /. Only one page should be active.
   */
  isActive?: boolean | null;
  /**
   * Add blocks in the order they should appear on the page.
   */
  blocks?:
    | {
        block: string | LandingBlock;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'user-notes';
        value: string | UserNote;
      } | null)
    | ({
        relationTo: 'schedule-slots';
        value: string | ScheduleSlot;
      } | null)
    | ({
        relationTo: 'groups';
        value: string | Group;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: string | Subscription;
      } | null)
    | ({
        relationTo: 'credit-transactions';
        value: string | CreditTransaction;
      } | null)
    | ({
        relationTo: 'documents';
        value: string | Document;
      } | null)
    | ({
        relationTo: 'payments';
        value: string | Payment;
      } | null)
    | ({
        relationTo: 'sick-leaves';
        value: string | SickLeaf;
      } | null)
    | ({
        relationTo: 'landing-blocks';
        value: string | LandingBlock;
      } | null)
    | ({
        relationTo: 'landing-pages';
        value: string | LandingPage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  lastName?: T;
  firstName?: T;
  middleName?: T;
  birthDate?: T;
  parentPhone?: T;
  role?: T;
  parent?: T;
  avatar?: T;
  timezone?: T;
  reminderLeadHours?: T;
  preferences?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-notes_select".
 */
export interface UserNotesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-slots_select".
 */
export interface ScheduleSlotsSelect<T extends boolean = true> {
  startAt?: T;
  durationMin?: T;
  kind?: T;
  student?: T;
  group?: T;
  status?: T;
  notes?: T;
  isRecurring?: T;
  recurrence?:
    | T
    | {
        frequency?: T;
        interval?: T;
        weekdays?: T;
        until?: T;
        count?: T;
        timezone?: T;
      };
  isRecurringChild?: T;
  recurrenceParent?: T;
  attendance?:
    | T
    | {
        student?: T;
        present?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups_select".
 */
export interface GroupsSelect<T extends boolean = true> {
  name?: T;
  members?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  student?: T;
  kind?: T;
  totalCredits?: T;
  remainingCredits?: T;
  validFrom?: T;
  validUntil?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-transactions_select".
 */
export interface CreditTransactionsSelect<T extends boolean = true> {
  student?: T;
  subscription?: T;
  slot?: T;
  delta?: T;
  reason?: T;
  balanceAfter?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  student?: T;
  docType?: T;
  title?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  student?: T;
  subscription?: T;
  amount?: T;
  currency?: T;
  periodFrom?: T;
  periodTo?: T;
  method?: T;
  paidAt?: T;
  receipt?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sick-leaves_select".
 */
export interface SickLeavesSelect<T extends boolean = true> {
  student?: T;
  slot?: T;
  reason?: T;
  document?: T;
  status?: T;
  reviewedAt?: T;
  reviewNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-blocks_select".
 */
export interface LandingBlocksSelect<T extends boolean = true> {
  title?: T;
  blockType?: T;
  heading?: T;
  subheading?: T;
  ctaText?: T;
  ctaTextSecondary?: T;
  backgroundImage?: T;
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cards?:
    | T
    | {
        icon?: T;
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              item?: T;
              id?: T;
            };
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        text?: T;
        id?: T;
      };
  dashboardCards?:
    | T
    | {
        label?: T;
        id?: T;
      };
  testimonials?:
    | T
    | {
        text?: T;
        rating?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        name?: T;
        price?: T;
        features?:
          | T
          | {
              item?: T;
              id?: T;
            };
        popular?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  advantages?:
    | T
    | {
        icon?: T;
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages_select".
 */
export interface LandingPagesSelect<T extends boolean = true> {
  title?: T;
  isActive?: T;
  blocks?:
    | T
    | {
        block?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}